services:
  - type: web
    name: axaliai-mainnet
    runtime: python
    buildCommand: ""
    startCommand: "python xparallel/server.py"
    healthCheckPath: /health
    envVars:
      - key: XP_TOKEN
        sync: false
      - key: XP_HOST
        value: 0.0.0.0
      - key: XP_NETWORK
        value: xparallel-mainnet
      - key: XP_VERSION
        value: 1.0.0
